### get all users
GET http://localhost:8000/api/users

### create a new user
POST http://localhost:8000/api/users
Content-Type: application/json

{
  "address": "",
  "birthday": "",
  "description": "",
  "email": "ddg",
  "firstname": "gdgdg",
  "lastname": "",
  "phone_number": ""
}